version: '3.1'
services:
  redis:
    image: redis:latest
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379

  api:
    build:
      context: './api'
      dockerfile: 'Dockerfile'
    volumes:
      - ./api:/api
      - ./api/package.json:/api/package.json
      - ./api/package-lock.json:/api/package-lock.json
      - ./api/node_modules:/api/node_modules
    ports:
      - 3000:3000
    depends_on:
      - redis
    tty: true
    working_dir: "/api"
    command: bash -c "yarn start"
