version: '3.1'
services:
  redis:
    image: redis:latest
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379

  mongodb:
    build:
      context: './mongodb'
      dockerfile: 'Dockerfile'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: MyApp
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data:/data/db
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: adminpassword
    depends_on:
      - mongodb

  api:
    build:
      context: './api'
      dockerfile: 'Dockerfile'
    environment:
      - MONGO_DATABASE=mongodb://staff:staff@mongodb:27017/MyApp
    volumes:
      - ./api:/api
      - ./api/package.json:/api/package.json
      - ./api/package-lock.json:/api/package-lock.json
      - ./api/node_modules:/api/node_modules
    ports:
      - 3000:3000
    depends_on:
      - redis
    tty: true
    working_dir: "/api"
    command: bash -c "yarn start"
